### ISSUE TITLE
PDF is buggy: Whitepaper: Managing Microsoft 365 with Microsoft365DSC and Azure DevOps

### ISSUE THREAD

**Issue by p-bojkowski** [microsoft/Microsoft365DSC#1630]
![image](https://user-images.githubusercontent.com/74313141/146372651-a1e9f6ea-7a42-43a9-8488-7a26bb500c98.png)

PDF content:

![image](https://user-images.githubusercontent.com/74313141/146372798-efa27be0-16ac-4779-b1c4-8db3a08b8314.png)

**Comment by p-bojkowski** [comment]
Same:

![image](https://user-images.githubusercontent.com/74313141/146373201-9c8dc26f-7abb-46d2-8b61-2b0309dc2346.png)

![image](https://user-images.githubusercontent.com/74313141/146373265-9508c8ca-09fe-43f3-a1d4-0876d77d860c.png)

**Comment by NikCharlebois** [comment]
Thanks for pointing this out. The url has been fixed now.

**Comment by ykuijs** [comment]
Updated this link as well! Thanks for letting us know!

**Comment by p-bojkowski** [comment]
@ykuijs the last Link isn't fixed: https://microsoft365dsc.com/Pages/Resources/Default.aspx

**Comment by ykuijs** [comment]
@p-bojkowski Where exactly do you see this link? When I click the "Other Microsoft365DSC content" link on https://github.com/microsoft/Microsoft365DSC/wiki, I am send to the correct link: https://microsoft365dsc.com/about/community-resources/
