### ISSUE TITLE
PowerShell freeze sometimes when Pnp is involved

### ISSUE THREAD

**Issue by Bender1983** [microsoft/Microsoft365DSC#1837]
I just noticed, when PnP  is involved sometimes the Script freezes after showing MFA-Auth (Config-Export with credentials).
PowerShell 5.1 with latest Microsoft365DSC. Could this be related to PnP? If yes then this bug could be closed.

Regards
Andreas

**Comment by andikrueger** [comment]
Hi Andreas,

Exporting a configuration with MFA enable should be working. What kind of PnP Version are you using? Is the PnP PowerShell registered as an application within the tenant and are the permissions approved? `Register-PnPManagementShellAccess` should add the required permissions scopes for the app.

**Comment by Bender1983** [comment]
Hi Andi

Register-PnPManagementShellAccess was missing but I still get freezes when the login for MFA appears and PnP is called. I use Powershell 5.1 wit PnP  1.9.0 on Server 2022. For me it looks like that its a problem with PnP. Found a lot hints/issues.

**Comment by andikrueger** [comment]
Thanks for the further details. Do you have an account without MFA? Would be good to have confirmation about the MFA dialog being the problem.

**Comment by Bender1983** [comment]
currently not but I can create one and can do testing with it, just give me some time

**Comment by informatik-bks** [comment]
Dear Andi

Sorry for my late reply, due medical problems I was a little bit longer away from work than expected. Today I tried to reproduce the bug. For testing purpose, I splited up the different workloads (instead of just single big export) and now I cant' reproduce the bug anymore.
If you wish you can close this issue, for us its solved but maybe this hint could be usefull for someone else.

Regards
Andreas

**Comment by andikrueger** [comment]
Thanks for the update! I'll close this issue for now.
