### ISSUE TITLE
AADAuthorizationPolicy fails on update

### ISSUE THREAD

**Issue by mlhickey** [microsoft/Microsoft365DSC#2103]
#### Details of the scenario you tried and the problem that is occurring
Attempting to update AuthorizationPolicy with new release fails.  Entry in eventvwr is:

**PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.**

#### Verbose logs showing the problem
VERBOSE: [M365-DSC-C1]: LCM:  [ Start  Set      ]  [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c]
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Setting configuration of AzureAD Authorization Policy
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Set-Targetresource: Running Get-TargetResource
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Getting configuration of AzureAD Authorization Policy
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Get-TargetResource: Found existing authorization policy
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c]  RoleName matching GuestUserRoleId is Guest
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] return Guest
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Get-TargetResource Result:
 AllowedToSignUpEmailBasedSubscriptions=True; AllowedToUseSSPR=True; AllowEmailVerifiedUsersToJoinOrganization=True; AllowInvitesFrom=everyone; ApplicationId=***;
ApplicationSecret=***; BlockMsolPowerShell=True; CertificateThumbprint=901E767819BA76BB97EF1A33837A19FF45A43332; Credential=$null; DefaultUserRoleAllowedToCreateApps=True;
DefaultUserRoleAllowedToCreateSecurityGroups=True; DefaultUserRoleAllowedToReadOtherUsers=False; Description=Used to manage authorization related settings across the company.;
 DisplayName=Authorization Policy; Ensure=Present; GuestUserRole=Guest; Id=authorizationPolicy; IsSingleInstance=Yes; PermissionGrantPolicyIdsAssignedToDefaultUserRole=();
TenantId=***
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Set-Targetresource: Cleaning up parameters
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Set-Targetresource: Authorization Policy Ensure Present
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'AllowEmailVerifiedUsersToJoinOrganization' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'DefaultUserRoleAllowedToReadOtherUsers' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'DisplayName' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Added 'PermissionGrantPolicyIdsAssignedToDefaultUserRole' to
UpdateParameters
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] added 'Verbose' to UpdateParameters
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'AllowInvitesFrom' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'GuestUserRole' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'AllowedToUseSSPR' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'DefaultUserRoleAllowedToCreateSecurityGroups' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'Id' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'DefaultUserRoleAllowedToCreateApps' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'BlockMsolPowerShell' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'AllowedToSignUpEmailBasedSubscriptions' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] 'Description' is unchanged
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Updating existing authorization policy with values:
PermissionGrantPolicyIdsAssignedToDefaultUserRole=(ManagePermissionGrantsForSelf.microsoft-user-default-legacy); Verbose=True
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] PowerShell Desired State Configuration does not support
execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation
prompt etc.
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-**4aae-a4d3-91b501a2c15c] Set-Targetresource: Failed change policy Authorization Policy
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] PowerShell Desired State Configuration does not support
execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation
prompt etc.**
VERBOSE: [M365-DSC-C1]:                            [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c] Set-Targetresource: finished processing Policy Authorization
Policy
VERBOSE: [M365-DSC-C1]: LCM:  [ End    Set      ]  [[AADAuthorizationPolicy]780781c4-b529-4aae-a4d3-91b501a2c15c]  in 0.4910 seconds.
#### Suggested solution to the issue
Add Id to param list for Get/Test/Set/Export.  Set- appears to require specific param name **AuthorizationPolicyId** rather than property name **Id**
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        AADAuthorizationPolicy 780781c4-b529-4aae-a4d3-91b501a2c15c
        {
            AllowedToSignUpEmailBasedSubscriptions            = $True;
            AllowedToUseSSPR                                  = $True;
            AllowEmailVerifiedUsersToJoinOrganization         = $True;
            AllowInvitesFrom                                  = "everyone";
            ApplicationId                                     = $ConfigurationData.NonNodeData.ApplicationId;
            BlockMsolPowerShell                               = $True;
            CertificateThumbprint                             = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DefaultUserRoleAllowedToCreateApps                = $True;
            DefaultUserRoleAllowedToCreateSecurityGroups      = $True;
            DefaultUserRoleAllowedToReadOtherUsers            = $False;
            Description                                       = "Used to manage authorization related settings across the company.";
            DisplayName                                       = "Authorization Policy";
            Ensure                                            = "Present";
            GuestUserRole                                     = "Guest";
            IsSingleInstance                                  = "Yes";
            PermissionGrantPolicyIdsAssignedToDefaultUserRole = @("ManagePermissionGrantsForSelf.microsoft-user-default-legacy");
            TenantId                                          = $ConfigurationData.NonNodeData.TenantId;
        }
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Datacenter Azure Edition
OsOperatingSystemSKU : 407
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev 
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.22.713.1 Microsoft365DSC                     {Add-M365DSCEvent, Add-M365DSCTelemetryEvent, Assert-M365DSCBlueprint, Compare-M365DSCConfigurations...}

**Comment by mlhickey** [comment]
Updated to version 1.22.720.1, now seeing the following in eventvwr

![image](https://user-images.githubusercontent.com/20215068/180614103-54a2a8bb-9820-4b39-81af-641dc297a469.png)

**Comment by mlhickey** [comment]
Updated to latest code, now seeing the following in eventvwr when drift is found:
![image](https://user-images.githubusercontent.com/20215068/180638452-0317b93d-4177-4b5a-931a-e5338a202367.png)
This is on VM running DSC instance in pull mode.

**Comment by mlhickey** [comment]
Think I found the problem - you transitioned to v1.0 in Get but left beta profile for Export (520/522)

**Comment by mlhickey** [comment]
One thing I did find - when you switched to v1.0 you left beta in the Export function

**Comment by NikCharlebois** [comment]
We cannot replicate. Is this error being thrown the first time you attempt to create the policy, when you try updating an existing one or when you try to remove it? Thanks

**Comment by mlhickey** [comment]
During update.  I'm going to re-baseline the env and retest

**Comment by mlhickey** [comment]
Added some additional logging, think I found the issue - Verbose isn't getting stripped when doing the param eval:
Checking DefaultUserRolePermissions values: Param -> AllowedToSignUpEmailBasedSubscriptions Desired -> True Current -> True "},
'AllowedToSignUpEmailBasedSubscriptions' is unchanged"},
**Checking DefaultUserRolePermissions values: Param -> Verbose Desired -> True Current ->  "},
added 'Verbose' to UpdateParameters"},**

**Comment by mlhickey** [comment]
Added some additional logging, think I found the issue - Verbose isn't getting stripped when doing the param eval:
Checking DefaultUserRolePermissions values: Param -> AllowedToSignUpEmailBasedSubscriptions Desired -> True Current -> True "},
'AllowedToSignUpEmailBasedSubscriptions' is unchanged"},
Checking DefaultUserRolePermissions values: Param -> Verbose Desired -> True Current -> "},
added 'Verbose' to UpdateParameters"},

**Comment by mlhickey** [comment]
DSC log with additional parameter tracing

[{15603A01-0C56-11ED-AED9-000D3A8F5258}-0.details.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9184574/15603A01-0C56-11ED-AED9-000D3A8F5258.-0.details.json.txt)

**Comment by mlhickey** [comment]
DSC log entry:
[{15603A01-0C56-11ED-AED9-000D3A8F5258}-0.details.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9184618/15603A01-0C56-11ED-AED9-000D3A8F5258.-0.details.json.txt)

**Comment by NikCharlebois** [comment]
Ok, I believe we found the issue. It only happened when the value of the PermissionGrantPolicyIdsAssignedToDefaultUserRole is null. We've just pushed a fix for it.

**Comment by mlhickey** [comment]
Copied the updated code, issue still exists for me.  Will try to dig into this today
![image](https://user-images.githubusercontent.com/20215068/181074083-e4e0227a-d8c0-4d9b-8ee4-3f245f365611.png)

![image](https://user-images.githubusercontent.com/20215068/181074145-4a493ca7-6af2-4ae1-8d9c-841afef3a166.png)

![image](https://user-images.githubusercontent.com/20215068/181074193-2a181a1d-db3f-4f6f-b7fd-a723ca64356e.png)

**Comment by mlhickey** [comment]
Grabbed the updated code, seems to be an issue with property evaluation, where it's incorrectly identifying drift, e.g.
![image](https://user-images.githubusercontent.com/20215068/181088880-1debcd53-1089-489c-906e-b13b82a5ee4c.png)

but in eventvwr:
![image](https://user-images.githubusercontent.com/20215068/181088984-e0da42e4-aacf-4f18-b221-994b525cf1c9.png)

**Comment by mlhickey** [comment]
Grabbed the updated code but still seems to be an issue with evaluation of PermissionGrantPolicyIdsAssignedToDefaultUserRole.  It incorrectly states drift though there's been no change which (I assume) then results in a failed update and associated eventlog error.  

![image](https://user-images.githubusercontent.com/20215068/181100785-7fe22ad7-d3aa-429d-9095-4bdefd1df9a1.png)


Will look at the code later today

**Comment by mlhickey** [comment]
BTW, did you notice that its mixing beta (Export) and v1.0  (Get).

**Comment by mlhickey** [comment]
Issue persists post-code fix, always on PermissionGrantPolicyIdsAssignedToDefaultUserRole when there is no change:

![image](https://user-images.githubusercontent.com/20215068/181129485-52c76486-69a8-4eec-8e5d-51d891b6cff3.png)

Something in the property evaluation seems to be awry

**Comment by NikCharlebois** [comment]
Good catch on the beta vs v1.0. However I am no longer able to replicate this issue with the latest code base. We are currently facing issues publishing version 1.22.727.1 (which would fix your issue) to the PowerShell Gallery. We are working with the PowerShell team to resolve the issue ASAP. Thanks

**Comment by mlhickey** [comment]
I think the problem may be that when where user consent is set to "Do not allow", the property value is supposed to be an empty array:

![image](https://user-images.githubusercontent.com/20215068/185719864-a638a5f1-355c-4b48-9de8-fd9a51f1a310.png)

The challenge may be that the value getting passed in is null which is invalid for an Update operation.

**Comment by mlhickey** [comment]
More insight:  When user consent is disallowed, value of PermissionGrantPoliciesAssigned is an empty string array.  If the desired state ivalue is ManagePermissionGrantsForSelf.microsoft-user-default-legacy it results in a series of 3 events - EVT1-3

![image](https://user-images.githubusercontent.com/20215068/185720921-50269508-2864-4062-9444-90babb066158.png)

Drift remediation starts with EVT1:
![image](https://user-images.githubusercontent.com/20215068/185720777-ef82d9f4-3d80-4871-8574-7bc25626299d.png)
followed by EVT2:
![image](https://user-images.githubusercontent.com/20215068/185720835-b096657a-9f37-449d-a5a9-1439e7e191b9.png)
which results in EVT3:
![image](https://user-images.githubusercontent.com/20215068/185720857-54b1f038-406b-41af-b3c3-c18988a86f6e.png)

**Comment by mlhickey** [comment]
Think the issue still exists around the PermissionGrantPolicyIdsAssignedToDefaultUserRole - null is valid when user consent is not allowed.  If an alternate value is desired, resource will correctly set but continues to throw the aforementioned error.  Will try researching over the weekend

**Comment by mlhickey** [comment]
Found that the additional null tests result in most items getting added to param list regardless of change state:

[run-with-single-comparison.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9389469/run-with-single-comparison.json.txt)
[run-with-extra-null-checks.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9389470/run-with-extra-null-checks.json.txt)

**Comment by mlhickey** [comment]
Found that the additional null tests result in most items getting added to param list regardless of change state
[run-with-extra-null-checks.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9389482/run-with-extra-null-checks.json.txt)
[run-with-single-comparison.json.txt](https://github.com/microsoft/Microsoft365DSC/files/9389492/run-with-single-comparison.json.txt)

:
