### ISSUE TITLE
Error Running: Export-M365DSCConfiguration ERROR: Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission.

### ISSUE THREAD

**Issue by sergioandreslq** [microsoft/Microsoft365DSC#3396]

**Comment by sergioandreslq** [comment]
![image](https://github.com/microsoft/Microsoft365DSC/assets/75001072/3d4e0be6-448b-4d5a-b75c-3e4577396247)


PS C:\Users\XXXXXX> get-computerinfo -property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')


OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB, fr-CA}


PS C:\Users\XXXX> get-M365DSCCompiledPermissionList -ResourceNameList @("AADApplication", "intuneDeviceCategory")

Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
RequiredRoles                  {}                                                                                                                                                                                                                                
Read                           {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable}                                                                                                          
RequiredRoleGroups             {}                                                                                                                                                                                                                                
Update                         {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable...}  


![image](https://github.com/microsoft/Microsoft365DSC/assets/75001072/93def0d1-04a4-4f07-be90-05d3bb414f31)

**Comment by sergioandreslq** [comment]
![image](https://github.com/microsoft/Microsoft365DSC/assets/75001072/bc114f10-0f72-4acc-9c99-c53f2c0e1dcc)

**Comment by sergioandreslq** [comment]
It was solved, I re-install, update and run the export command.

**Comment by jpcapone** [comment]
I am having this same issue and i attempted to uninstall and reinstall number times but I am still getting the same error.  I have also run the following:
```
Update-Module Microsoft365DSC
Update-M365DSCDependencies
```
any suggestions would be appreciated.

**Comment by nicojdejong** [comment]
I have a similar error using from powershell 5.1 and in 7.3.6 (after also going through https://microsoft365dsc.com/user-guide/get-started/powershell7-support/).

Exception: Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission.

After some back and forth - I tried Connect-PnPOnline and I got a (more clear) error on app registration consent and followed the advise here - https://www.sharepointdiary.com/2021/08/fix-connect-pnponline-aadsts65001-user-or-administrator-has-not-consented-to-use-the-application.html - This solved the issue.

**Comment by nicojdejong** [comment]
I have a similar error using from powershell 5.1 and in 7.3.6 (after also going through https://microsoft365dsc.com/user-guide/get-started/powershell7-support/).

Exception: Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission.

After some back and forth - I tried Connect-PnPOnline and I got an error on app registration consent and followed the advis here - https://www.sharepointdiary.com/2021/08/fix-connect-pnponline-aadsts65001-user-or-administrator-has-not-consented-to-use-the-application.html - This solved the issue.

**Comment by DarioBonini** [comment]
Same error,
Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission.
