### ISSUE TITLE
Support for Azure/O365 Government (GCC, GCCH) Environments?

### ISSUE THREAD

**Issue by hbwheat** [microsoft/Microsoft365DSC#930]
Hello, I've tried to glean some old issues mentioning "GCC" or "GCCH" to determine what the support is like for DSC within those environments. One that looked promising regarding errors and maybe fixes was moved to back channel comms.

So, is there an update or general information on the support for US Gov environments specifically I'm interested in GCC High. I can assist with GCCH testing if need be too.... 

Some modules seem to work some fail...  I know from experience different dependencies/modules support different clouds, well, differently in stating where they should connect. I tried tracing through the code mentions of GCCH. I couldn't reliably determine how the authentication/endpoints where specifying the source or if I could for an environment variable. They mostly seem to only point to Az/O365 Public by default.

So I'm curious !

**Comment by desmay** [comment]
@hbwheat I use M365DSC for my customer in GCC using Azure Application authentication for SPO and OneDrive workloads. Currently there is a bug using accounts which are MFA enabled but it should be resolved on this week upcoming release. We also run integration tests on a GCC tenant. I'm not sure if we have anyone try GCCH yet but any testing and reporting of bugs would be much appreciated.

**Comment by hbwheat** [comment]
@desmay, I'll be on the lookout for the MFA bug fix and test from there. I did see in the testing files "GCCH" is referenced, but not actively tested? 
Oddly enough I'm really only familiar with Public and GCC High. I'll throw out that many, if not all, the endpoints are different (*.us) for GCCH and many of the O365 modules need to use an environment parameter to work. I did run the Export cmdlt to a GCCH tenant and it routinely kept breaking on AAD and EXO modules. I couldn't trace errors to specific to why, but I suspect it falls back to the environment parameter or authentication methods used.

**Comment by hbwheat** [comment]
@desmay, is it possible to run the Export without exiting on first failure? I bet some errors are critical, but I'd like to go through each module and see what fails and what does work (assuming _something_ works already)... without having to uncheck boxes or adjust the run command.

**Comment by desmay** [comment]
@hbwheat Are you using the latest version of M365DSC ? It should continue to run even if it encounters an error with a specific resource

**Comment by hbwheat** [comment]
@desmay, I'm running version 1.20.1118.1. I'm not sure if that's the current or not.

Running from the CLI I had better luck before it failed to a stop. It made to 93/111 modules with some errors being ignored. 
Another thing, It's only writing the error log  and not any modules that made it processed.

**Comment by desmay** [comment]
@hbwheat Are you using a user account or Azure AD application ? This version does have issue with MFA enabled accounts if you are using a user account. Any chance you can post any of the error messages in logs ?

**Comment by hbwheat** [comment]
@desmay, using an account with MFA. For an AAD app is there a known set of API permissions that need to be granted and I can try that route?

**Comment by hbwheat** [comment]
@desmay , so once MFA bug is fixed for the user account, I'll need to double check permissions for EXO and SP by the looks of the lags as that is where it errored out. However, I still can't see what was export thus far..

**Comment by desmay** [comment]
@hbwheat For permissions for AAD app you can review this wiki page - https://github.com/Microsoft/Microsoft365DSC/wiki/ODSP-Permissions . The fix was pushed to Github and if you would like to try now you should be able to run install-m365DSCDevBranch or if you prefer it should be released to Powershell gallery on Wednesday 11/25

You should see a file M365TenantConfig.ps1 that contains the exported contents in the directory you specified in export path.

**Comment by hbwheat** [comment]
@desmay , awesome I'll give it a try.

**Comment by hbwheat** [comment]
@desmay, I'm still not getting a partial export even after specifying the Path and Filename.

**Comment by desmay** [comment]
@hbwheat Any chance you can post error file or at least provide some details of the errors you are getting ? Also can you post the command you are executing for export as well

**Comment by hbwheat** [comment]
@desmay, error causing an exit:

```
    |---[1/5] Commodity Exchange ActRemoved the PSSession ExchangeOnlineInternalSession_31 connected to ps.compliance.protection.office365.us
[67/111] Extracting [SCFilePlanPropertyDepartment]...New-ExoPSSession : An error occurred while sending the request..
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.1\ExchangeOnlineManagement.psm1:481 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession

```

Run CLI command:
```
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('O365AdminAuditLogConfig','O365OrgCustomizationSetting','EXOAcceptedDomain','EXOActiveSyncDeviceAccessRule','EXOAddressBookPolicy','EXOAddressList','EXOAntiPhishPolicy','EXOAntiPhishRule','EXOApplicationAccessPolicy','EXOAtpPolicyForO365','EXOAvailabilityAddressSpace','EXOAvailabilityConfig','EXOCASMailboxPlan','EXOClientAccessRule','EXODkimSigningConfig','EXOEmailAddressPolicy','EXOGlobalAddressList','EXOHostedConnectionFilterPolicy','EXOHostedContentFilterPolicy','EXOHostedContentFilterRule','EXOHostedOutboundSpamFilterPolicy','EXOInboundConnector','EXOIntraOrganizationConnector','EXOMailTips','EXOMalwareFilterPolicy','EXOMalwareFilterRule','EXOMobileDeviceMailboxPolicy','EXOOfflineAddressBook','EXOOnPremisesOrganization','EXOOrganizationConfig','EXOOrganizationRelationship','EXOOutboundConnector','EXOOwaMailboxPolicy','EXOPartnerApplication','EXOPolicyTipConfig','EXORemoteDomain','EXORoleAssignmentPolicy','EXOSafeAttachmentPolicy','EXOSafeAttachmentRule','EXOSafeLinksPolicy','EXOSafeLinksRule','EXOSharedMailbox','EXOSharingPolicy','IntuneAppConfigurationPolicy','IntuneDeviceCategory','ODSettings','SPOAccessControlSettings','SPOApp','SPOHomeSite','SPOHubSite','SPOOrgAssetsLibrary','SPOSearchManagedProperty','SPOSearchResultSource','SPOSharingSettings','SPOSiteDesign','SPOSiteDesignRights','SPOSiteScript','SPOStorageEntity','SPOTenantCdnEnabled','SPOTenantCdnPolicy','SPOTenantSettings','SPOTheme','SCAuditConfigurationPolicy','SCCaseHoldPolicy','SCCaseHoldRule','SCComplianceCase','SCComplianceSearch','SCComplianceSearchAction','SCComplianceTag','SCDeviceConditionalAccessPolicy','SCDeviceConfigurationPolicy','SCDLPCompliancePolicy','SCDLPComplianceRule','SCFilePlanPropertyAuthority','SCFilePlanPropertyCategory','SCFilePlanPropertyCitation','SCFilePlanPropertyDepartment','SCFilePlanPropertyReferenceId','SCFilePlanPropertySubCategory','SCLabelPolicy','SCRetentionCompliancePolicy','SCRetentionComplianceRule','SCRetentionEventType','SCSensitivityLabel','SCSupervisoryReviewPolicy','SCSupervisoryReviewRule','TeamsCallingPolicy','TeamsChannelsPolicy','TeamsClientConfiguration','TeamsEmergencyCallingPolicy','TeamsEmergencyCallRoutingPolicy','TeamsGuestCallingConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingConfiguration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsMessagingPolicy','TeamsPstnUsage','TeamsTenantDialPlan','TeamsUpgradeConfiguration','TeamsUpgradePolicy','TeamsVoiceRoute','TeamsVoiceRoutingPolicy','AADApplication','AADGroupsNamingPolicy','AADGroupsSettings','AADMSGroupLifecyclePolicy','AADPolicy','AADTenantDetails') -GlobalAdminAccount 'redact@' -Path (Get-Location) -FileName ("M365_DSC_" + (Get-Date -Format "MM-dd-yyyy-hh:mm") + ".ps1")
```

**Comment by hbwheat** [comment]
As well for this error, it stopped writing the error log to a separate text file in the local directory.

**Comment by desmay** [comment]
Can you try the following:
`Test-MSCloudLogin -Platform SecurityComplianceCenter`
`Get-FilePlanPropertyDepartment`

**Comment by hbwheat** [comment]
@desmay, both worked, no errors. 

```
VERBOSE: Trying to connect to platform {SecurityComplianceCenter}
VERBOSE: ConnectionUrl = https://ps.compliance.protection.office365.us/powershell-liveid/
VERBOSE: AuthorizationUrl = https://login.microsoftonline.us/common
Removed the PSSession ExchangeOnlineInternalSession_33 connected to ps.compliance.protection.office365.us
```

**Comment by desmay** [comment]
@hbwheat Good. Lets try breaking down extract into small chucks while troubleshooting. These are the valid workloads 'AAD', 'SPO', 'EXO', 'INTUNE', 'SC', 'OD', 'O365', 'TEAMS', 'PP', 'PLANNER'

We can target specific workloads so for example SharePoint Online:

`Export-M365DSCConfiguration -Quiet -Workloads @("SPO")  -GlobalAdminAccount 'redact@' -Path (Get-Location) -FileName ("M365_DSC_" + (Get-Date -Format "MM-dd-yyyy-hh:mm") + ".ps1")`

You can also just target specific resources so something like
``Export-M365DSCConfiguration -Quiet -ComponentsToExtract "ODSettings"  -GlobalAdminAccount 'redact@' -Path (Get-Location) -FileName ("M365_DSC_" + (Get-Date -Format "MM-dd-yyyy-hh:mm") + ".ps1"`

**Comment by NikCharlebois** [comment]
@hbwheat Ben, have we been able to isolate the issue to a specific workload like @desmay Derek is suggesting above? Thanks

**Comment by hbwheat** [comment]
@NikCharlebois , Hey I'm sorry with the delay. I will be running tests soon and will report back.  I have not forgotten and will do it. :-)

**Comment by hbwheat** [comment]
@desmay , okayyy information for you...

I went down 2 paths. The first was by by components I hand picked (73). These looked most relevant of what I want to work with right now. The second was by workload (this takes much longer to run). I'll provide an update on that when it's done running through.

**1st (components):**

73 components to use Export-M365DSCConfiguration

`'O365AdminAuditLogConfig','O365OrgCustomizationSetting','EXOActiveSyncDeviceAccessRule','EXOAddressBookPolicy','EXOAntiPhishPolicy','EXOAntiPhishRule','EXOApplicationAccessPolicy','EXOAtpPolicyForO365','EXOClientAccessRule','EXOEmailAddressPolicy','EXOHostedConnectionFilterPolicy','EXOHostedContentFilterPolicy','EXOHostedContentFilterRule','EXOHostedOutboundSpamFilterPolicy','EXOMailTips','EXOMalwareFilterPolicy','EXOMalwareFilterRule','EXOMobileDeviceMailboxPolicy','EXOOrganizationConfig','EXOOwaMailboxPolicy','EXOPolicyTipConfig','EXORoleAssignmentPolicy','EXOSafeAttachmentPolicy','EXOSafeAttachmentRule','EXOSafeLinksPolicy','EXOSafeLinksRule','EXOSharingPolicy','IntuneAppConfigurationPolicy','IntuneDeviceCategory','ODSettings','SPOAccessControlSettings','SPOSharingSettings','SPOSiteAuditSettings','SPOTenantSettings','SCAuditConfigurationPolicy','SCCaseHoldPolicy','SCCaseHoldRule','SCComplianceCase','SCComplianceTag','SCDeviceConditionalAccessPolicy','SCDeviceConfigurationPolicy','SCDLPCompliancePolicy','SCDLPComplianceRule','SCFilePlanPropertyAuthority','SCFilePlanPropertyCategory','SCFilePlanPropertyCitation','SCFilePlanPropertyDepartment','SCFilePlanPropertyReferenceId','SCFilePlanPropertySubCategory','SCLabelPolicy','SCRetentionCompliancePolicy','SCRetentionComplianceRule','SCRetentionEventType','SCSensitivityLabel','SCSupervisoryReviewPolicy','SCSupervisoryReviewRule','TeamsCallingPolicy','TeamsChannelsPolicy','TeamsClientConfiguration','TeamsEmergencyCallingPolicy','TeamsEmergencyCallRoutingPolicy','TeamsGuestCallingConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingConfiguration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsMessagingPolicy','AADGroupsSettings','AADMSGroupLifecyclePolicy','AADPolicy','AADTenantDetails'`

Total error count of the 73 modules selected was 14. Fatal errors required removing the module from the list to continue. Errors that "continued" are labeled as such below.

**14 components that had errors:**
```
'ODSettings','TeamsCallingPolicy','TeamsChannelsPolicy','TeamsClientConfiguration','TeamsEmergencyCallingPolicy','TeamsEmergencyCallRoutingPolicy','TeamsGuestCallingConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingConfiguration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsMessagingPolicy'
```


(continuted)
```
ODSettings
[1/1] Extracting [ODSettings]...Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:202 char:9
+         $tenantName = $defaultDomain[0].Name.Replace($domain, '')
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

(fatal)
```
TeamsCallingPolicy
[1/1] Extracting [TeamsCallingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

(fatal)
```
TeamsChannelsPolicy
[1/1] Extracting [TeamsChannelsPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

(continued)
```
TeamsClientConfiguration
[1/1] Extracting [TeamsClientConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(fatal)
```
TeamsEmergencyCallingPolicy
[1/1] Extracting [TeamsEmergencyCallingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

(fatal)
```
TeamsEmergencyCallRoutingPolicy
[1/1] Extracting [TeamsEmergencyCallRoutingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

(continued)
```
TeamsGuestCallingConfiguration
[1/1] Extracting [TeamsGuestCallingConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(continued)
```
TeamsGuestMeetingConfiguration
[1/1] Extracting [TeamsGuestMeetingConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(continued)
```
TeamsGuestMessagingConfiguration
[1/1] Extracting [TeamsGuestMessagingConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(continued)
```
TeamsMeetingBroadcastConfiguration
[1/1] Extracting [TeamsMeetingBroadcastConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(fatal)
```
TeamsMeetingBroadcastPolicy
[1/1] Extracting [TeamsMeetingBroadcastPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

(continued) 
```
TeamsMeetingConfiguration
[1/1] Extracting [TeamsMeetingConfiguration]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
```

(fatal)
```
TeamsMeetingPolicy
[1/1] Extracting [TeamsMeetingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSessio
```

(fatal)
```
TeamsMessagingPolicy
[1/1] Extracting [TeamsMessagingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: unknown_user_type: Unknown User Type
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.42\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
```

**Comment by hbwheat** [comment]
**2nd Workloads**

These are very similar to the above components of course. For the information it did I haven't combined through yet. 

- AAD
  - Pulled apps, tenant details, user principals, etc..
- EXO
  - Quite a bit here covering what looks like everything.
- INTUNE
  - This pulled no information.
- O365
   - Pulled users, groups, and some org configurations.
- OD
  - This pulled no information.
- SC
  - This pulled file plans and retention event types.
- SPO
  - This doesn't fail but it pulls no data. 
- TEAMS
  - This is fails on start.

When a module pulled no data I see the following in the .ps1: 
```
Node localhost
{
}
```

**Comment by hbwheat** [comment]
Of course this is all reverse DSC. At some point I'll want to try and go the other way. I'm curious if components that worked will work in the other direction too.

**Comment by hbwheat** [comment]
Commands:
```
$components = @('O365AdminAuditLogConfig','O365OrgCustomizationSetting','EXOActiveSyncDeviceAccessRule','EXOAddressBookPolicy','EXOAntiPhishPolicy','EXOAntiPhishRule','EXOApplicationAccessPolicy','EXOAtpPolicyForO365','EXOClientAccessRule','EXOEmailAddressPolicy','EXOHostedConnectionFilterPolicy','EXOHostedContentFilterPolicy','EXOHostedContentFilterRule','EXOHostedOutboundSpamFilterPolicy','EXOMailTips','EXOMalwareFilterPolicy','EXOMalwareFilterRule','EXOMobileDeviceMailboxPolicy','EXOOrganizationConfig','EXOOwaMailboxPolicy','EXOPolicyTipConfig','EXORoleAssignmentPolicy','EXOSafeAttachmentPolicy','EXOSafeAttachmentRule','EXOSafeLinksPolicy','EXOSafeLinksRule','EXOSharingPolicy','IntuneAppConfigurationPolicy','IntuneDeviceCategory','ODSettings','SPOAccessControlSettings','SPOSharingSettings','SPOSiteAuditSettings','SPOTenantSettings','SCAuditConfigurationPolicy','SCCaseHoldPolicy','SCCaseHoldRule','SCComplianceCase','SCComplianceTag','SCDeviceConditionalAccessPolicy','SCDeviceConfigurationPolicy','SCDLPCompliancePolicy','SCDLPComplianceRule','SCFilePlanPropertyAuthority','SCFilePlanPropertyCategory','SCFilePlanPropertyCitation','SCFilePlanPropertyDepartment','SCFilePlanPropertyReferenceId','SCFilePlanPropertySubCategory','SCLabelPolicy','SCRetentionCompliancePolicy','SCRetentionComplianceRule','SCRetentionEventType','SCSensitivityLabel','SCSupervisoryReviewPolicy','SCSupervisoryReviewRule','TeamsCallingPolicy','TeamsChannelsPolicy','TeamsClientConfiguration','TeamsEmergencyCallingPolicy','TeamsEmergencyCallRoutingPolicy','TeamsGuestCallingConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingConfiguration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsMessagingPolicy','AADGroupsSettings','AADMSGroupLifecyclePolicy','AADPolicy','AADTenantDetails')

$workloads= @(
    'AAD', 'SPO', 'EXO', 'INTUNE', 'SC', 'OD', 'O365', 'TEAMS'
)

$workingPath = ""
$creds = Get-Credential

$components |  %{$_;Export-M365DSCConfiguration -Quiet -ComponentsToExtract $_ -GlobalAdminAccount $creds -FileName ($_ + "_reverseDSC" + ".ps1") -Path ($workingPath + '\components\' + $_)}

$workloads |  %{$_;Export-M365DSCConfiguration -Quiet -Workloads $_ -GlobalAdminAccount $creds -FileName ($_ + "_reverseDSC" + ".ps1") -Path ($workingPath + '\modules\' + $_)}

```

**Comment by desmay** [comment]
@hbwheat The global admin account you used was it an @onmicrosoft.com account ?

**Comment by hbwheat** [comment]
@desmay, yes it was. Should I try with a domain?

**Comment by desmay** [comment]
@hbwheat No we sometime saw issues with custom domains. It looks like issue is with MSCloudLoginAssistant with Teams and SPO /OD4B workloads. 

I'm assuming this will fail: 
`Test-MSCloudLogin -Platform PnP
Get-PnPTenant
`

**Comment by hbwheat** [comment]
@desmay,  I had to install the AzureADPreview module for it to not error out. It returns nothing however. Is that expected?

**Comment by desmay** [comment]
@hbwheat It should have displayed your tenant information. We'll look into issue with MSCloudLoginAssistant & GCCH
