### ISSUE TITLE
always receive error The PowerShell DSC resource MSFT_SPOAccessControlSettings from module <Microsoft365DSC,1.20.1125.1> does not exist

### ISSUE THREAD

**Issue by ckuever** [microsoft/Microsoft365DSC#940]
we always receive the following error on a Server 2019:

The PowerShell DSC resource MSFT_SPOAccessControlSettings from module <Microsoft365DSC,1.20.1125.1> does not exist at he PowerShell module path nor is it registered as a WMI DSC resource.

get-dscressource clearly shows that the dsc resource is available.

**Comment by NikCharlebois** [comment]
@ckuever we are not able to replicate on our end with 1.20.1125.1. 

get-dscresource -Module Microsoft365DSC | Select-Object Name, ModuleName, Version                                                                                                                                                    Name                               ModuleName      Version                                                              ----                               ----------      -------                                                              AADApplication                     Microsoft365DSC 1.20.1125.1                                                          AADGroupsNamingPolicy              Microsoft365DSC 1.20.1125.1                                                          AADGroupsSettings                  Microsoft365DSC 1.20.1125.1                                                          AADMSGroup                         Microsoft365DSC 1.20.1125.1                                                          AADMSGroupLifecyclePolicy          Microsoft365DSC 1.20.1125.1                                                          AADPolicy                          Microsoft365DSC 1.20.1125.1                                                          AADRoleDefinition                  Microsoft365DSC 1.20.1125.1                                                          AADServicePrincipal                Microsoft365DSC 1.20.1125.1                                                          AADTenantDetails                   Microsoft365DSC 1.20.1125.1                                                          EXOAcceptedDomain                  Microsoft365DSC 1.20.1125.1                                                          EXOActiveSyncDeviceAccessRule      Microsoft365DSC 1.20.1125.1                                                          EXOAddressBookPolicy               Microsoft365DSC 1.20.1125.1                                                          EXOAddressList                     Microsoft365DSC 1.20.1125.1                                                          EXOAntiPhishPolicy                 Microsoft365DSC 1.20.1125.1                                                          EXOAntiPhishRule                   Microsoft365DSC 1.20.1125.1                                                          EXOApplicationAccessPolicy         Microsoft365DSC 1.20.1125.1                                                          EXOAtpPolicyForO365                Microsoft365DSC 1.20.1125.1                                                          EXOAvailabilityAddressSpace        Microsoft365DSC 1.20.1125.1                                                          EXOAvailabilityConfig              Microsoft365DSC 1.20.1125.1                                                          EXOCASMailboxPlan                  Microsoft365DSC 1.20.1125.1                                                          EXOClientAccessRule                Microsoft365DSC 1.20.1125.1                                                          EXODkimSigningConfig               Microsoft365DSC 1.20.1125.1                                                          EXOEmailAddressPolicy              Microsoft365DSC 1.20.1125.1                                                          EXOGlobalAddressList               Microsoft365DSC 1.20.1125.1                                                          EXOHostedConnectionFilterPolicy    Microsoft365DSC 1.20.1125.1                                                          EXOHostedContentFilterPolicy       Microsoft365DSC 1.20.1125.1                                                          EXOHostedContentFilterRule         Microsoft365DSC 1.20.1125.1                                                          EXOHostedOutboundSpamFilterPolicy  Microsoft365DSC 1.20.1125.1                                                          EXOInboundConnector                Microsoft365DSC 1.20.1125.1                                                          EXOIntraOrganizationConnector      Microsoft365DSC 1.20.1125.1                                                          EXOMailboxSettings                 Microsoft365DSC 1.20.1125.1                                                          EXOMailTips                        Microsoft365DSC 1.20.1125.1                                                          EXOMalwareFilterPolicy             Microsoft365DSC 1.20.1125.1                                                          EXOMalwareFilterRule               Microsoft365DSC 1.20.1125.1                                                          EXOManagementRole                  Microsoft365DSC 1.20.1125.1                                                          EXOMobileDeviceMailboxPolicy       Microsoft365DSC 1.20.1125.1                                                          EXOOfflineAddressBook              Microsoft365DSC 1.20.1125.1                                                          EXOOnPremisesOrganization          Microsoft365DSC 1.20.1125.1                                                          EXOOrganizationConfig              Microsoft365DSC 1.20.1125.1                                                          EXOOrganizationRelationship        Microsoft365DSC 1.20.1125.1                                                          EXOOutboundConnector               Microsoft365DSC 1.20.1125.1                                                          EXOOwaMailboxPolicy                Microsoft365DSC 1.20.1125.1                                                          EXOPartnerApplication              Microsoft365DSC 1.20.1125.1                                                          EXOPolicyTipConfig                 Microsoft365DSC 1.20.1125.1                                                          EXORemoteDomain                    Microsoft365DSC 1.20.1125.1                                                          EXORoleAssignmentPolicy            Microsoft365DSC 1.20.1125.1                                                          EXOSafeAttachmentPolicy            Microsoft365DSC 1.20.1125.1                                                          EXOSafeAttachmentRule              Microsoft365DSC 1.20.1125.1                                                          EXOSafeLinksPolicy                 Microsoft365DSC 1.20.1125.1                                                          EXOSafeLinksRule                   Microsoft365DSC 1.20.1125.1                                                          EXOSharedMailbox                   Microsoft365DSC 1.20.1125.1                                                          EXOSharingPolicy                   Microsoft365DSC 1.20.1125.1                                                          IntuneAppConfigurationPolicy       Microsoft365DSC 1.20.1125.1                                                          IntuneDeviceCategory               Microsoft365DSC 1.20.1125.1                                                          O365AdminAuditLogConfig            Microsoft365DSC 1.20.1125.1                                                          O365Group                          Microsoft365DSC 1.20.1125.1                                                          O365OrgCustomizationSetting        Microsoft365DSC 1.20.1125.1                                                          O365User                           Microsoft365DSC 1.20.1125.1                                                          ODSettings                         Microsoft365DSC 1.20.1125.1                                                          PlannerBucket                      Microsoft365DSC 1.20.1125.1                                                          PlannerPlan                        Microsoft365DSC 1.20.1125.1                                                          PlannerTask                        Microsoft365DSC 1.20.1125.1                                                          PPPowerAppsEnvironment             Microsoft365DSC 1.20.1125.1                                                          SCAuditConfigurationPolicy         Microsoft365DSC 1.20.1125.1                                                          SCCaseHoldPolicy                   Microsoft365DSC 1.20.1125.1                                                          SCCaseHoldRule                     Microsoft365DSC 1.20.1125.1                                                          SCComplianceCase                   Microsoft365DSC 1.20.1125.1                                                          SCComplianceSearch                 Microsoft365DSC 1.20.1125.1                                                          SCComplianceSearchAction           Microsoft365DSC 1.20.1125.1                                                          SCComplianceTag                    Microsoft365DSC 1.20.1125.1                                                          SCDeviceConditionalAccessPolicy    Microsoft365DSC 1.20.1125.1                                                          SCDeviceConfigurationPolicy        Microsoft365DSC 1.20.1125.1                                                          SCDLPCompliancePolicy              Microsoft365DSC 1.20.1125.1                                                          SCDLPComplianceRule                Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertyAuthority        Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertyCategory         Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertyCitation         Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertyDepartment       Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertyReferenceId      Microsoft365DSC 1.20.1125.1                                                          SCFilePlanPropertySubCategory      Microsoft365DSC 1.20.1125.1                                                          SCLabelPolicy                      Microsoft365DSC 1.20.1125.1                                                          SCRetentionCompliancePolicy        Microsoft365DSC 1.20.1125.1                                                          SCRetentionComplianceRule          Microsoft365DSC 1.20.1125.1                                                          SCRetentionEventType               Microsoft365DSC 1.20.1125.1                                                          SCSensitivityLabel                 Microsoft365DSC 1.20.1125.1                                                          SCSupervisoryReviewPolicy          Microsoft365DSC 1.20.1125.1                                                          SCSupervisoryReviewRule            Microsoft365DSC 1.20.1125.1                                                          **SPOAccessControlSettings**           Microsoft365DSC 1.20.1125.1                                                          SPOApp                             Microsoft365DSC 1.20.1125.1                                                          SPOHomeSite                        Microsoft365DSC 1.20.1125.1                                                          SPOHubSite                         Microsoft365DSC 1.20.1125.1                                                          SPOOrgAssetsLibrary                Microsoft365DSC 1.20.1125.1                                                          SPOPropertyBag                     Microsoft365DSC 1.20.1125.1                                                          SPOSearchManagedProperty           Microsoft365DSC 1.20.1125.1                                                          SPOSearchResultSource              Microsoft365DSC 1.20.1125.1                                                          SPOSharingSettings                 Microsoft365DSC 1.20.1125.1                                                          SPOSite                            Microsoft365DSC 1.20.1125.1                                                          SPOSiteAuditSettings               Microsoft365DSC 1.20.1125.1                                                          SPOSiteDesign                      Microsoft365DSC 1.20.1125.1                                                          SPOSiteDesignRights                Microsoft365DSC 1.20.1125.1                                                          SPOSiteGroup                       Microsoft365DSC 1.20.1125.1                                                          SPOSiteScript                      Microsoft365DSC 1.20.1125.1                                                          SPOStorageEntity                   Microsoft365DSC 1.20.1125.1                                                          SPOTenantCdnEnabled                Microsoft365DSC 1.20.1125.1                                                          SPOTenantCDNPolicy                 Microsoft365DSC 1.20.1125.1                                                          SPOTenantSettings                  Microsoft365DSC 1.20.1125.1                                                          SPOTheme                           Microsoft365DSC 1.20.1125.1                                                          SPOUserProfileProperty             Microsoft365DSC 1.20.1125.1                                                          TeamsCallingPolicy                 Microsoft365DSC 1.20.1125.1                                                          TeamsChannel                       Microsoft365DSC 1.20.1125.1                                                          TeamsChannelsPolicy                Microsoft365DSC 1.20.1125.1                                                          TeamsClientConfiguration           Microsoft365DSC 1.20.1125.1                                                          TeamsEmergencyCallingPolicy        Microsoft365DSC 1.20.1125.1                                                          TeamsEmergencyCallRoutingPolicy    Microsoft365DSC 1.20.1125.1
TeamsGuestCallingConfiguration     Microsoft365DSC 1.20.1125.1
TeamsGuestMeetingConfiguration     Microsoft365DSC 1.20.1125.1
TeamsGuestMessagingConfiguration   Microsoft365DSC 1.20.1125.1
TeamsMeetingBroadcastConfiguration Microsoft365DSC 1.20.1125.1
TeamsMeetingBroadcastPolicy        Microsoft365DSC 1.20.1125.1
TeamsMeetingConfiguration          Microsoft365DSC 1.20.1125.1
TeamsMeetingPolicy                 Microsoft365DSC 1.20.1125.1
TeamsMessagingPolicy               Microsoft365DSC 1.20.1125.1
TeamsPstnUsage                     Microsoft365DSC 1.20.1125.1
TeamsTeam                          Microsoft365DSC 1.20.1125.1
TeamsTenantDialPlan                Microsoft365DSC 1.20.1125.1
TeamsUpgradeConfiguration          Microsoft365DSC 1.20.1125.1
TeamsUpgradePolicy                 Microsoft365DSC 1.20.1125.1
TeamsUser                          Microsoft365DSC 1.20.1125.1
TeamsVoiceRoute                    Microsoft365DSC 1.20.1125.1
TeamsVoiceRoutingPolicy            Microsoft365DSC 1.20.1125.1

**Comment by NikCharlebois** [comment]
Can you check if you are able to import the .psm1 with -verbose without any issues?

Import-Module <path>\MSFT_SPOAccessControlSettings.psm1 -Verbose

**Comment by ckuever** [comment]
get-dscresource -Module Microsoft365DSC | Select-Object Name, ModuleName, Version

exactly the same output then on your screenshot

the import-module directly from the folder works.

![image](https://user-images.githubusercontent.com/33624101/100346986-f8e8fe00-2fe4-11eb-9261-9c72a78c9de5.png)

**Comment by ckuever** [comment]
we are starting the scripts from azure devops pipeline on a Server 2019 agent VM

**Comment by NikCharlebois** [comment]
Ok, and SPOAccessControl is the only one causing problems? Or is it because it is the first for SPO in alphabetical order being hit?

**Comment by ckuever** [comment]
i think because it's the first in alphabetical order being hit

devops pipeline log output:

![image](https://user-images.githubusercontent.com/33624101/100347869-5a5d9c80-2fe6-11eb-9902-682899ace626.png)

**Comment by NikCharlebois** [comment]
This is going to be hard for us to troubleshoot remotely, but have you had a look at @ykuijs whitepaper on setting up M365DSC with ADO?
https://microsoft365dsc.com/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

**Comment by ckuever** [comment]
yes of course, good whitepaper. as we have knowledge in devops i don't think it's a wrong pipeline or something like this. 

Somehow in the dcs ressources / module in combination with server 2019? i will also try to find the error...

**Comment by ckuever** [comment]
it works locally via start-dscconfiguration on the server, so error is somehow related to the devops pipeline task:

winrm quickconfig -force
Start-DscConfiguration -Path "$(System.ArtifactsDirectory)\_dbs-m365-blueprints-SPO\MOFFile" -Verbose -Wait -Force
if ($error.Count -gt 0)
{
 write-host "the following errors occurred during dscconfiguration";
 write-host ($error | fl * | out-string );
 throw $error[-1];
}

**Comment by cloudignition** [comment]
> it works locally via start-dscconfiguration on the server, so error is somehow related to the devops pipeline task:
> 
> winrm quickconfig -force
> Start-DscConfiguration -Path "$(System.ArtifactsDirectory)_dbs-m365-blueprints-SPO\MOFFile" -Verbose -Wait -Force
> if ($error.Count -gt 0)
> {
> write-host "the following errors occurred during dscconfiguration";
> write-host ($error | fl * | out-string );
> throw $error[-1];
> }

ckuever, 

Any luck figuring this out? My build worked a week ago on version 1111 and i started getting this same error on 1125. Seems like something was a breaking change.

**Comment by ckuever** [comment]
cloudignition,

strange, no i cannot confirm, same error also with version 1111

is it still working with 1111 in your case when you revert back to version 1111

can you share your winrm config and exact devops task? 

thank you.

**Comment by NikCharlebois** [comment]
Looping in @ykuijs in case he has an idea.

**Comment by NikCharlebois** [comment]
Couple of questions for you folks since we are not able to replicate on our end:

1 - You are not seeing any issues in the build pipeline compiling that MOF file, correct?

2 - If you are able to get your hands on that MOF file, are you properly seeing a reference to SPOAccessControlSettings in it?

3 - If you are able to get your hands on that MOF file, can you try running it locally?

4 - Where are you installing the module from? A different task in the same pipeline? Here's the pipeline's task I was using in my tests, which works for me. It's a single task Release pipeline. Could you also try it as a test to see if that works for you as well?

winrm quickconfig -force
Install-Module Microsoft365DSC -Force -AllowClobber
cd '_SPO - Compile Configuration\DSC'
Start-DSCConfiguration SPO -Wait -Verbose -Force

**Comment by cloudignition** [comment]
> Couple of questions for you folks since we are not able to replicate on our end:
> 
> 1 - You are not seeing any issues in the build pipeline compiling that MOF file, correct?
> 
> 2 - If you are able to get your hands on that MOF file, are you properly seeing a reference to SPOAccessControlSettings in it?
> 
> 3 - If you are able to get your hands on that MOF file, can you try running it locally?
> 
> 4 - Where are you installing the module from? A different task in the same pipeline? Here's the pipeline's task I was using in my tests, which works for me. It's a single task Release pipeline. Could you also try it as a test to see if that works for you as well?
> 
> winrm quickconfig -force
> Install-Module Microsoft365DSC -Force -AllowClobber
> cd '_SPO - Compile Configuration\DSC'
> Start-DSCConfiguration SPO -Wait -Verbose -Force

Here is my list of events. (for SPOSharingSettings, but i suspect its all modules)

I started working on this Nov 23. Everything worked fine on my local machine with version 1118.

Nov 23, added a build pipeline in ADO and it built the MOF fine. Pipeline pulled latest version on that day. 

Nov 30 added a release pipeline, started getting the above error that @ckuever reported. 

Nov 30 re-ran the build pipeline, now getting that error on the mof build. Never had it before on there.

Nov 30 Installed M365DSC on my surface pro (never had been there before, latest version), getting same error when trying to compile the MOF. 

Nov 30 Reverted to 1111 and still receiving the error. Error occurs on both the MOF compile and apply in build and release for me. 

Dec 1, Checked my PC which originally worked. It still works on 1111. Updated to 1125 and it still works.

**Comment by NikCharlebois** [comment]
Let me know if you are able to reproduce when trying Q4 above. We need to be able to replicate on our end first to be able to take this any further.

**Comment by ckuever** [comment]
Start-DSCConfiguration locally works for me also with both versions and even with the compiled mof file out of the devops built-pipeline. Only running the release pipeline out of devops seems to cause that issue. We currently facing it with a Server 2019 (where devops agent is running). we will try to see if it's OS related via trying with a Server 2016 also. 

@Nik: that's our release pipeline script (nearly the same then in devops guide). 

winrm quickconfig -force
Start-DscConfiguration -Path "$(System.ArtifactsDirectory)_dbs-m365-blueprints-SPO\MOFFile" -Verbose -Wait -Force
if ($error.Count -gt 0)
{
write-host "the following errors occurred during dscconfiguration";
write-host ($error | fl * | out-string );
throw $error[-1];
}

**Comment by NikCharlebois** [comment]
Thanks I understand that the code above is your pipeline, but where are you installing the module from? Any chances that the hosted agent has multiple version of M365DSC installed on it which may be conflicting with one another?

**Comment by cloudignition** [comment]
> Let me know if you are able to reproduce when trying Q4 above. We need to be able to replicate on our end first to be able to take this any further.

I use the same single task inline powershell as yours.

**Comment by ckuever** [comment]
no, no multiple versions exist on hosted agent, verified via powershell and so on

the module is installed during built pipeline on the agent host via prep.ps1: (we currently forced to 1.20.1111.1 for testing)

Write-Output "Checking for Microsoft365Dsc module"

$psGallery = Find-Module Microsoft365Dsc -RequiredVersion 1.20.1111.1
$localModule = Get-Module Microsoft365Dsc -List

if ($localModule.Version -ne $psGallery.Version)
{
    $M365DscPath = 'C:\Program Files\WindowsPowerShell\Modules\Microsoft365Dsc'
    if (Test-Path -Path $M365DscPath)
    {
        Write-Output "Removing old version of Microsoft365Dscdule"
        Remove-Item -Path $M365DscPath -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\AzureAD' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\DSCParser' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups.Planner' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.ConditionalAccess' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Intune' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Planner' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\ReverseDSC' -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\SharePointPnPPowerShellOnline' -Force -Recurse -ErrorAction SilentlyContinue
    }

    Write-Output "Installing Microsoft365Dsc"
    Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
    Install-Module -Name 'Microsoft365Dsc' -RequiredVersion 1.20.1111.1 -AllowClobber -Force
}

module path also covered in PSModulePath:

![image](https://user-images.githubusercontent.com/33624101/100752048-5ff12300-33e8-11eb-82d6-d360195461ab.png)

**Comment by cloudignition** [comment]
> we will try to see if it's OS related via trying with a Server 2016 also.

I use a 2016 build agent, so its cross OS.

**Comment by cloudignition** [comment]
I figured out my issue. My PS1 config file was calling a specific module version that was no longer being installed because new versions had been released and therefore the file was calling an old module. I stripped the -ModuleVersion and it began working again. Another option would be to use -RequiredVersion or -MaximumVersion on the built agent module install so that the config file called version matches the installed version.

**Comment by NikCharlebois** [comment]
Thanks for closing the loop. We're glad your issue has been solved.

**Comment by ckuever** [comment]
i always stipped the -ModuleVersion but the problem still exists. i read somewhere that it might be related to MMaagent beeing installed :

https://www.iditect.com/how-to/55109102.html

will try also to remove MMAagent from PSModulePath but so far issue is not resolved...

**Comment by NikCharlebois** [comment]
Significant changes were recently made to the dependency engine. Can you please confirm if you are still facing this issue with the latest version of the module? Thanks

**Comment by soundd2** [comment]
Hi NIkCharlebois, This is shyam, Sorry for the interruption, I am also facing similar issue.   I followed below whitepaper provided by Ykuji, It is almost done. But for me it is failing at the release pipeline. 
https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

Please find the log screenshot here: 

![image](https://user-images.githubusercontent.com/94822959/167243343-331e465b-b3f3-49e9-bf9a-0537d9457aa0.png)
![image](https://user-images.githubusercontent.com/94822959/167243369-8b71b0b7-35d3-4268-ba74-ab4b2a626923.png)
![image](https://user-images.githubusercontent.com/94822959/167243387-c510fd6e-64e2-4cc4-ac8d-14ad5c90b1d9.png)

Please help on this.
